from pathlib import Path
root=Path('/Users/nani/workspace/upwork-job-demos/publish')
items={
'cybersecurity-gtm-outbound-engine':{
 'title':'Cybersecurity GTM Outbound Engine',
 'eyebrow':'Clay + Instantly + Pipedrive proof-of-approach · fictional data only',
 'lead':'A clean outbound operating system for a UK cybersecurity firm: ICP targeting, Clay enrichment, 4-inbox Instantly sequencing, deliverability guardrails, reply routing into Pipedrive, and handoff docs.',
 'chips':['UK SMEs 50–500','Cyber assurance / CE+','4 warmed inboxes','Clay waterfalls','Instantly sequences','Pipedrive replies'],
 'modules':[('ICP waterfall','Prioritize professional services, legal/accounting, SaaS/fintech, manufacturing and security-conscious SMEs by pain + buying trigger.'),('Clay enrichment QA','Company size, sector, tech stack, likely M365/security review need, decision-maker role, verified email and confidence score.'),('Instantly launch guardrails','Low-volume sending logic, inbox rotation, suppression rules, reply categories and deliverability-safe escalation.'),('Pipedrive handoff','Positive replies, meeting requests and objection patterns land as clean activities/deals with source campaign context.'),('Handover system','Loom + written SOP: list logic, campaign changes, deliverability checks, troubleshooting, and scale rules.')],
 'deliverable':'First milestone: map ICP + build one working Clay → Instantly → Pipedrive campaign path, then document the operating rules before scaling the remaining segments.'
},
'ghl-sales-operations-crm-architecture':{
 'title':'GoHighLevel Sales-to-Operations CRM Architecture',
 'eyebrow':'GHL CRM architecture proof · fictional data only',
 'lead':'A full sales-to-operations CRM blueprint for a service business: Lead Capture → Qualification → Estimation → Quote Submitted → Follow-Up → Won/Lost → Project Intake → Live Project dashboards.',
 'chips':['GHL pipelines','Estimation workflow','Opportunity scoring','Follow-up rules','Project handoff','KPI dashboards'],
 'modules':[('Pipeline governance','Stage rules, required fields, ownership logic and leakage checks so deals do not sit unmanaged.'),('Qualification + scoring','Budget, competitors, profitability, priority and next-step logic visible before estimation starts.'),('Estimation/BOQ tracking','Start/completion/submission dates, revision state, owner visibility and quote handoff status.'),('Won → intake automation','Trigger checklist, assign owner, capture revenue value, category and live-project state.'),('Executive dashboards','Lead response time, quote-to-meeting, quote-to-win, BOQ turnaround, source revenue and closed revenue.')],
 'deliverable':'First milestone: build the core pipeline, required fields, movement rules and dashboard skeleton, then test the handoff from won deal to project intake.'
},
'clickup-multi-client-fabrication-template':{
 'title':'ClickUp Multi-Client PM Template',
 'eyebrow':'ClickUp workspace/template proof · fictional data only',
 'lead':'A reusable ClickUp model Space for a metal fabrication shop: Jobs, Quotes & Contracts, Social Media, Operations, guest sharing, cross-entity My Work view, and duplicatable handoff docs.',
 'chips':['Jobs board','Quotes & Contracts','Operations','Guest sharing','Custom fields','Template handoff'],
 'modules':[('Jobs Kanban','Lead → Quoted → Approved → In Fabrication → Ready → Delivered/Invoiced → Paid/Closed + On Hold.'),('Custom fields','Client, job type, job value, due date, deposit received, site/location and priority.'),('Multi-entity structure','One fully-realized model Space that can be duplicated as new clients/entities are added.'),('Controlled sharing','Guest/member access limited to the Jobs List while internal operations remain private.'),('Handoff docs','Short maintenance guide for duplicating the template, updating statuses and keeping My Work clean.')],
 'deliverable':'First milestone: build one complete model Space, configure the Jobs board/custom fields/views, then provide a concise duplication and maintenance guide.'
}
}
css='''*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Arial;background:radial-gradient(circle at 10% 0%,#38bdf855,transparent 30%),linear-gradient(180deg,#06111f,#080b12 60%,#05070b);color:#f8fafc}.wrap{max-width:1160px;margin:auto;padding:46px 20px 72px}.hero{border:1px solid #243244;background:linear-gradient(135deg,#101827f2,#0b1020d9);border-radius:30px;padding:34px;box-shadow:0 24px 80px #0008}.eyebrow{display:inline-flex;border:1px solid #38bdf899;background:#38bdf81a;color:#dff7ff;border-radius:999px;padding:9px 13px;font-size:13px}h1{font-size:clamp(36px,6vw,68px);line-height:.95;letter-spacing:-.055em;margin:18px 0 14px}.lead{font-size:20px;line-height:1.55;color:#cbd5e1;max-width:900px}.chips{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.chips span{border:1px solid #334155;background:#0f172a;padding:10px 12px;border-radius:999px;color:#dbeafe;font-size:13px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin:24px 0}.card{border:1px solid #27354a;background:#0b1220;border-radius:22px;padding:18px;min-height:190px}.num{width:34px;height:34px;border-radius:11px;background:#38bdf81a;color:#7dd3fc;display:grid;place-items:center;font-weight:900;margin-bottom:13px}.card b{display:block;color:#fff;margin-bottom:9px}.card span{font-size:14px;line-height:1.45;color:#9fb0c7}.panel{display:grid;grid-template-columns:1fr .9fr;gap:18px}.box{border:1px solid #27354a;background:#0b1220d9;border-radius:24px;padding:24px}.flow{display:grid;gap:11px}.step{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #1e293b;padding:12px 0;color:#cbd5e1}.step:last-child{border-bottom:0}.cta{border-left:4px solid #38bdf8;background:#082f4933;border-radius:14px;padding:16px;color:#e0f2fe}.small{margin-top:18px;color:#94a3b8;font-size:13px}@media(max-width:900px){.grid,.panel{grid-template-columns:1fr}h1{font-size:40px}}'''
for slug,d in items.items():
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{d['title']}</title><style>{css}</style></head><body><main class="wrap"><section class="hero"><div class="eyebrow">{d['eyebrow']}</div><h1>{d['title']}</h1><p class="lead">{d['lead']}</p><div class="chips">{''.join(f'<span>{c}</span>' for c in d['chips'])}</div></section><section class="grid">{''.join(f'<article class="card"><div class="num">{i}</div><b>{name}</b><span>{txt}</span></article>' for i,(name,txt) in enumerate(d['modules'],1))}</section><section class="panel"><div class="box"><h2>First build plan</h2><div class="flow"><div class="step"><span>1. Confirm fields/access</span><strong>systems + owners</strong></div><div class="step"><span>2. Build core path</span><strong>trigger → logic → output</strong></div><div class="step"><span>3. Add QA rules</span><strong>dedupe + error checks</strong></div><div class="step"><span>4. Test with sample/live-safe data</span><strong>before handoff</strong></div><div class="step"><span>5. Document operations</span><strong>Loom + written SOP</strong></div></div></div><div class="box"><h2>Delivery angle</h2><p class="cta">{d['deliverable']}</p><p class="small">This is a lightweight proof-of-approach for the Upwork post. All names/data are fictional and no client systems were accessed.</p></div></section></main></body></html>'''
    p=root/slug/'index.html'; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(html)
print('created', ', '.join(items))
