from pathlib import Path
from textwrap import dedent
base=Path('/Users/nani/workspace/upwork-job-demos')
jobs=[
('twilio-whatsapp-ai-assistant-mvp','Twilio WhatsApp AI Assistant MVP','Twilio WhatsApp Business API → webhooks → OpenAI conversation flow with templates, session logic, handoff notes, and clean Node/Python architecture.',['Twilio webhook intake for inbound WhatsApp messages','Conversation/session state with safe fallback logic','OpenAI reply layer with system prompt + business rules','Template/message status tracker and error log','MVP build plan for 4–6 week scope'], '$4,800'),
('crm-workflow-automation-architect','CRM Workflow Automation Command Center','Make/Zapier/API CRM workflows for lead routing, status updates, duplicate checks, and operational visibility.',['Lead intake and normalized field mapping','CRM pipeline routing with owner/status rules','Make/Zapier/API modules with retry/error handling','Duplicate prevention and audit log','Handoff documentation for internal team'], '$600'),
('dental-ai-voice-receptionist-production','Dental AI Voice Receptionist Production Checklist','Vapi/ElevenLabs/Make webhook system for dental office calls: patient data capture, appointment workflow, notifications, and production-readiness checks.',['Call flow and dental FAQ guardrails','8-point patient intake capture','Post-call webhook to Make/CRM/Sheet','Office notification + follow-up SMS logic','Production QA checklist for reliability and compliance dependencies'], '$500'),
('dtc-lead-acquisition-machine','DTC Lead Acquisition Machine','Qualified Shopify/DTC prospect discovery → enrichment → HubSpot records → personalized outreach sequence drafts without mass-spam behavior.',['ICP filter for Shopify/DTC brands and outdated site signals','Decision-maker enrichment and source confidence score','HubSpot contact/company creation mapping','Personalized 3-email sequence draft generation','Quality controls: dedupe, suppression, review queue'], '$300'),
]
css='''
:root{--bg:#090d14;--card:#111827;--muted:#94a3b8;--text:#e5eefb;--accent:#63e6be;--blue:#60a5fa;--warn:#fbbf24}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Arial;background:radial-gradient(circle at top left,#142036,#090d14 48%);color:var(--text)}main{max-width:1100px;margin:0 auto;padding:54px 22px}.eyebrow{color:var(--accent);font-weight:700;letter-spacing:.08em;text-transform:uppercase;font-size:12px}.hero{padding:34px;border:1px solid #223047;border-radius:28px;background:linear-gradient(135deg,rgba(17,24,39,.95),rgba(15,23,42,.7));box-shadow:0 24px 70px rgba(0,0,0,.35)}h1{font-size:clamp(34px,5vw,62px);line-height:.95;margin:14px 0}p{color:var(--muted);font-size:18px;line-height:1.65}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin:26px 0}.module{background:rgba(15,23,42,.88);border:1px solid #26354e;border-radius:18px;padding:18px;min-height:150px}.module b{display:block;color:#fff;margin-bottom:8px}.num{width:34px;height:34px;border-radius:11px;background:rgba(99,230,190,.12);color:var(--accent);display:grid;place-items:center;font-weight:800;margin-bottom:12px}.panel{display:grid;grid-template-columns:1.15fr .85fr;gap:18px;margin-top:18px}.box{border:1px solid #25334c;border-radius:22px;background:rgba(2,6,23,.55);padding:22px}.row{display:flex;justify-content:space-between;border-bottom:1px solid #1e293b;padding:12px 0;color:#cbd5e1}.row:last-child{border-bottom:0}.badge{display:inline-flex;gap:8px;align-items:center;border:1px solid #31506e;border-radius:999px;padding:8px 12px;color:#bfdbfe;background:rgba(96,165,250,.08);font-size:14px;margin:6px 6px 0 0}.cta{margin-top:22px;padding:18px;border-left:4px solid var(--accent);background:rgba(99,230,190,.08);border-radius:14px;color:#d1fae5}.small{font-size:13px;color:#94a3b8;margin-top:18px}@media(max-width:850px){.grid,.panel{grid-template-columns:1fr}h1{font-size:40px}}
'''
template='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{css}</style></head><body><main><section class="hero"><div class="eyebrow">Project-specific proof of approach · fictional data only</div><h1>{title}</h1><p>{subtitle}</p><div><span class="badge">Fixed-price target: {budget}</span><span class="badge">Fast V1 / MVP scope</span><span class="badge">Clean handoff notes</span></div></section><section class="grid">{modules}</section><section class="panel"><div class="box"><h2>How I would build the first milestone</h2><div class="row"><span>1. Scope map</span><strong>fields, systems, access, edge cases</strong></div><div class="row"><span>2. Core workflow</span><strong>trigger → logic → output</strong></div><div class="row"><span>3. Reliability</span><strong>dedupe, retry, error log</strong></div><div class="row"><span>4. Testing</span><strong>sample/live-safe records</strong></div><div class="row"><span>5. Handoff</span><strong>short docs + next steps</strong></div></div><div class="box"><h2>Client-safe notes</h2><p>This is a lightweight architecture/workflow mockup built for the Upwork post. It uses fictional data and does not claim live access to the client's systems.</p><div class="cta">The goal is not just making the automation run once — it is making it reliable enough that the team can trust it daily.</div></div></section><p class="small">Prepared by Janis as a proof-of-approach for this specific Upwork project.</p></main></body></html>'''
for slug,title,subtitle,mods,budget in jobs:
    modules=''.join(f'<article class="module"><div class="num">{i}</div><b>{m.split()[0]} {m.split()[1] if len(m.split())>1 else ""}</b><span>{m}</span></article>' for i,m in enumerate(mods,1))
    path=base/'publish'/slug/'index.html'
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(template.format(title=title,subtitle=subtitle,modules=modules,budget=budget,css=css),encoding='utf-8')
print('created',len(jobs),'demos')
