from pathlib import Path
from textwrap import dedent

ROOT=Path('/Users/nani/workspace/upwork-job-demos')
JOBS=[
 dict(slug='ai-agent-n8n-openai-command-center', accent='#7c3aed', title='AI Agent & n8n Automation Command Center', subtitle='Production-style proof for AI agents, OpenAI workflows, n8n orchestration, CRM/API integrations, chatbot routing, and reliability monitoring.', budget='$10,000 fixed', stack='n8n · OpenAI · CRM APIs · Webhooks · Supabase · Slack/Telegram/WhatsApp', modules=['AI intake router classifies requests and routes to agent/workflow','n8n orchestration board with retries, branches, and webhook payloads','CRM/API sync layer with lead status, notes, and escalation flags','Prompt/version control panel for safer production behavior','Ops log showing failed runs, latency, retries, and handoff notes'], metrics=[('Workflows mapped','12'),('API routes','18'),('Error states covered','9'),('Handoff docs','Ready')], events=['New lead qualified by AI agent','CRM status updated after webhook validation','Fallback path triggered for missing API field','Human handoff sent to Slack + Telegram'], cta='A lean first milestone would map the client use cases, build one production-grade n8n workflow, add API/webhook error handling, then document deployment and scaling options.'),
 dict(slug='ats-job-posting-pipeline-control-room', accent='#0891b2', title='ATS Job-Posting Pipeline Control Room', subtitle='Google Sheets / Apps Script workflow for company-owned career pages, platform-specific ATS connectors, OpenAI classification, logs, and operator-friendly retries.', budget='$500 fixed', stack='Google Sheets · Apps Script · Workday · ADP · UKG · Greenhouse · OpenAI', modules=['Connector health for Workday, ADP Workforce Now, ADP MyJobs, UKG, Greenhouse, Paycor','Normalized JOBS_RAW output with company, title, location, URL, description, source, raw JSON','OpenAI classification queue for labor-market intelligence signals','COMPANY_SCORES tab model with transparent scoring reasons','LOGS panel with graceful per-company failures instead of crashed runs'], metrics=[('ATS connectors','6'),('Normalized fields','8'),('Bad URL handling','Isolated'),('Operator logging','Clear')], events=['Workday feed discovered and normalized','ADP connector skipped one invalid URL without stopping run','OpenAI classification wrote ERP complexity score','Company-level score refreshed with source caveats'], cta='First milestone: stabilize the six existing ATS connectors, normalize outputs, preserve the Sheets workflow, and make logs simple enough for a non-programmer operator.'),
 dict(slug='hubspot-landing-page-build-qa-system', accent='#f97316', title='HubSpot Landing Page Build & QA System', subtitle='Build-ready proof for HubSpot CMS landing pages: investor lead capture, booking pages, RSVP pages, campaign microsites, modular templates, and QA handoff.', budget='$300 fixed', stack='HubSpot CMS · HTML/CSS · Forms · Scheduler · Campaign QA · Modular Templates', modules=['Page build queue for investor, booking, RSVP, and microsite campaigns','HubSpot module checklist: forms, scheduler links, thank-you states, hidden fields','Responsive QA board with mobile/tablet/desktop checks','A/B variant tracker so the internal team can reuse sections','Handoff notes for copy/design/paid media/HubSpot ops team'], metrics=[('Page types','4'),('QA checks','26'),('Reusable modules','8'),('Handoff format','Team-ready')], events=['Investor lead page passed form + CRM field test','Booking page scheduler link verified','RSVP page mobile layout flagged and fixed','Template section marked reusable for next campaign'], cta='First milestone: build one production-ready HubSpot landing page from wireframes/assets, verify forms/scheduler/mobile QA, then hand over reusable modules and notes.'),
 dict(slug='hr-ai-automation-integration-delivery-board', accent='#22c55e', title='HR AI Automation Integration Delivery Board', subtitle='Low-code delivery board for HR/recruitment automations: Make/Zapier, API integrations, OpenAI JSON, chatbot flows, and client-ready implementation tracking.', budget='$500 fixed', stack='Make · Zapier · OpenAI · JSON · APIs · HR/Recruitment Workflows · Chatbot', modules=['Client intake map for HR/recruitment agency automations','Make/Zapier build stages with triggers, filters, routers, and API calls','OpenAI JSON step with schema validation and fallback prompts','Chatbot handoff path for candidate/client conversations','QA and documentation checklist for repeatable client delivery'], metrics=[('Automation stages','7'),('API touchpoints','11'),('JSON checks','5'),('Repeatable docs','Included')], events=['Candidate intake routed through AI scoring step','Malformed JSON caught before CRM update','Client status notification sent from Make router','Reusable implementation notes generated for next HR client'], cta='First milestone: pick one HR use case, map the exact trigger/action flow, build the Make/Zapier automation, add JSON validation, test sample records, and document reuse.'),
]

BASE_CSS='''
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#070711;color:#f8fafc}body:before{content:"";position:fixed;inset:0;background:radial-gradient(circle at 20% 0%,var(--accent) 0,transparent 28%),radial-gradient(circle at 85% 10%,#0ea5e9 0,transparent 22%),linear-gradient(145deg,#070711 0%,#111827 60%,#020617 100%);opacity:.34;z-index:-2}.wrap{max-width:1180px;margin:0 auto;padding:42px 22px 70px}.hero{display:grid;grid-template-columns:1.15fr .85fr;gap:24px;align-items:stretch}.panel{background:rgba(15,23,42,.74);border:1px solid rgba(148,163,184,.18);border-radius:28px;box-shadow:0 24px 80px rgba(0,0,0,.35);backdrop-filter:blur(18px)}.hero-main{padding:38px}.badge{display:inline-flex;gap:8px;align-items:center;padding:8px 12px;border:1px solid color-mix(in srgb,var(--accent),white 30%);border-radius:999px;background:color-mix(in srgb,var(--accent),transparent 84%);color:#fff;font-size:13px;font-weight:700}.badge span{width:8px;height:8px;border-radius:99px;background:var(--accent);box-shadow:0 0 22px var(--accent)}h1{font-size:clamp(34px,5vw,64px);line-height:.96;margin:24px 0 18px;letter-spacing:-.055em}.sub{font-size:19px;line-height:1.55;color:#cbd5e1;max-width:780px}.disclaimer{margin-top:18px;padding:12px 14px;border-left:3px solid var(--accent);background:rgba(255,255,255,.055);border-radius:12px;color:#e2e8f0;font-size:13px}.cta{margin-top:24px;font-size:15px;color:#e5e7eb}.side{padding:26px;display:flex;flex-direction:column;gap:16px}.kpi{display:grid;grid-template-columns:1fr 1fr;gap:12px}.kpi div,.event,.module,.step{background:rgba(2,6,23,.58);border:1px solid rgba(148,163,184,.14);border-radius:18px;padding:16px}.kpi b{font-size:30px;color:white;display:block}.kpi span{font-size:12px;color:#94a3b8;text-transform:uppercase;letter-spacing:.08em}.stack{font-size:14px;color:#cbd5e1;line-height:1.6}.section{margin-top:26px;display:grid;grid-template-columns:1fr 1fr;gap:24px}.section h2{margin:0 0 16px;font-size:25px;letter-spacing:-.03em}.modules,.events{display:grid;gap:12px}.module{display:grid;grid-template-columns:34px 1fr;gap:12px;align-items:start}.num{width:34px;height:34px;border-radius:12px;background:var(--accent);display:grid;place-items:center;font-weight:900}.module p,.event p{margin:0;color:#cbd5e1;line-height:1.45}.flow{margin-top:26px;padding:24px}.flowgrid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.step strong{display:block;margin-bottom:8px}.step small{color:#94a3b8;line-height:1.45}.footer{margin-top:28px;color:#94a3b8;font-size:13px;text-align:center}@media(max-width:850px){.hero,.section,.flowgrid{grid-template-columns:1fr}.hero-main{padding:26px}.wrap{padding:24px 14px 44px}h1{font-size:38px}.kpi{grid-template-columns:1fr 1fr}}
'''

def html(job):
    mods=''.join(f'<div class="module"><div class="num">{i}</div><p>{m}</p></div>' for i,m in enumerate(job['modules'],1))
    metrics=''.join(f'<div><b>{v}</b><span>{k}</span></div>' for k,v in job['metrics'])
    events=''.join(f'<div class="event"><p>{e}</p></div>' for e in job['events'])
    steps=''.join(f'<div class="step"><strong>{a}</strong><small>{b}</small></div>' for a,b in [('Map','Confirm exact systems, fields, roles, and success criteria.'),('Build','Ship the first working workflow/page/connector with clean structure.'),('Test','Use sample/live-safe data and capture edge cases before handoff.'),('Handoff','Document setup, caveats, and how the client can expand it.')])
    return dedent(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{job['title']}</title><style>:root{{--accent:{job['accent']}}}{BASE_CSS}</style></head><body><main class="wrap"><section class="hero"><div class="hero-main panel"><div class="badge"><span></span> Project-specific proof · {job['budget']}</div><h1>{job['title']}</h1><p class="sub">{job['subtitle']}</p><div class="disclaimer">Fictional demo data only. This page is a proof-of-approach for the Upwork workflow, not a claim that these exact client systems are already connected.</div><p class="cta">{job['cta']}</p></div><aside class="side panel"><h2>Execution snapshot</h2><div class="kpi">{metrics}</div><div class="stack"><strong>Stack:</strong><br>{job['stack']}</div></aside></section><section class="section"><div class="panel" style="padding:24px"><h2>Workflow modules</h2><div class="modules">{mods}</div></div><div class="panel" style="padding:24px"><h2>Live operations log</h2><div class="events">{events}</div></div></section><section class="flow panel"><h2>First milestone path</h2><div class="flowgrid">{steps}</div></section><div class="footer">Built as a fast client-facing proof page for Janis Agic · clear workflow, concrete first milestone, no fake proof.</div></main></body></html>''')

for job in JOBS:
    d=ROOT/'publish'/job['slug']
    d.mkdir(parents=True, exist_ok=True)
    (d/'index.html').write_text(html(job), encoding='utf-8')
print('\n'.join(str(ROOT/'publish'/j['slug']/'index.html') for j in JOBS))
