from pathlib import Path
root=Path('/Users/nani/workspace/upwork-job-demos/publish')

def page(title, subtitle, accent, sections, metrics, workflow, slug):
    cards=''.join(f'<div class="card"><div class="label">{k}</div><div class="value">{v}</div></div>' for k,v in metrics)
    mods=''.join(f'<section class="panel"><h3>{h}</h3><p>{p}</p><ul>'+''.join(f'<li>{x}</li>' for x in bullets)+'</ul></section>' for h,p,bullets in sections)
    steps=''.join(f'<div class="step"><b>{i+1}. {s[0]}</b><span>{s[1]}</span></div>' for i,s in enumerate(workflow))
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>
:root{{--a:{accent};--bg:#080b12;--panel:#101827;--muted:#94a3b8;--text:#e5eefc;--line:#22304a}}*{{box-sizing:border-box}}body{{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Arial;background:radial-gradient(circle at 20% 0%,color-mix(in srgb,var(--a) 26%,transparent),transparent 38%),linear-gradient(135deg,#07101d,#0b1020 55%,#080b12);color:var(--text)}}.wrap{{max-width:1180px;margin:0 auto;padding:34px 18px 70px}}.hero{{display:grid;grid-template-columns:1.2fr .8fr;gap:22px;align-items:stretch}}.box,.panel,.step{{background:rgba(16,24,39,.82);border:1px solid var(--line);border-radius:22px;box-shadow:0 20px 70px rgba(0,0,0,.28)}}.box{{padding:30px}}.eyebrow{{color:var(--a);font-weight:800;letter-spacing:.08em;text-transform:uppercase;font-size:12px}}h1{{font-size:clamp(34px,5vw,62px);line-height:.98;margin:12px 0 14px}}p{{color:#c6d3e5;line-height:1.65}}.disc{{display:inline-block;margin:10px 0 18px;padding:8px 12px;border:1px solid color-mix(in srgb,var(--a) 45%,#334155);background:rgba(255,255,255,.04);border-radius:999px;color:#dbeafe;font-size:13px}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:18px}}.card{{padding:16px;border-radius:17px;background:#0b1220;border:1px solid #26344f}}.label{{font-size:12px;color:var(--muted)}}.value{{font-size:23px;font-weight:900;margin-top:6px}}.flow{{display:grid;gap:12px}}.step{{padding:16px}}.step b{{display:block;color:#fff;margin-bottom:6px}}.step span{{color:#a9b8cd;font-size:14px}}.modules{{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-top:24px}}.panel{{padding:22px}}.panel h3{{margin:0 0 8px;font-size:20px}}li{{margin:8px 0;color:#cbd5e1}}.cta{{margin-top:24px;padding:18px;border-radius:18px;background:linear-gradient(90deg,color-mix(in srgb,var(--a) 18%,transparent),rgba(255,255,255,.03));border:1px solid color-mix(in srgb,var(--a) 35%,#334155)}}@media(max-width:850px){{.hero,.modules{{grid-template-columns:1fr}}.grid{{grid-template-columns:repeat(2,1fr)}}}}</style></head><body><main class="wrap"><div class="hero"><div class="box"><div class="eyebrow">Project-specific proof of approach</div><h1>{title}</h1><p>{subtitle}</p><div class="disc">Fictional sample data only — built to show workflow, QA logic, and handoff structure for this exact Upwork project.</div><div class="grid">{cards}</div></div><div class="flow">{steps}</div></div><div class="modules">{mods}</div><div class="cta"><b>First milestone approach:</b> map inputs and success criteria, build the first review/automation board, run sample-data validation, then document exact handoff steps so the client can approve safely before production work.</div></main></body></html>'''
    d=root/slug; d.mkdir(parents=True,exist_ok=True); (d/'index.html').write_text(html)

page('Spectral Analysis Review Board','A compact analysis workspace for comparing six guided-audio reference tracks: spectrogram view, frequency-band notes, loudness consistency, stereo movement, loop/section markers, and production recommendations before the client finalizes their wellness audio pipeline.','#38bdf8',[
('Reference track intake','Each track gets a structured row instead of vague audio notes.',['file/source label','track purpose: breathwork, entrainment, voice bed, transition','first-pass issue tags','sample-task ready export']),
('Spectral + dynamics review','Focus on technical differences the client can act on.',['low/mid/high band balance','RMS/LUFS consistency notes','harshness/masking hotspots','stereo width and movement']),
('Production pipeline recommendations','Turns analysis into a decision document.',['which sonic traits to copy or avoid','safe volume/headroom targets','voice/music balance guidance','handoff notes for producer']),
('Paid sample task structure','Keeps the first step small and reviewable.',['analyze 1–2 tracks first','deliver annotated report','confirm format','then complete remaining references'])],
[('Sample task','1–2 tracks'),('Full review','6 tracks'),('Output','Technical report'),('Risk','Low/no account access')],
[('Import references','Add the six audio files and note intended use.'),('Analyze bands','Spectrogram, loudness, dynamics, stereo and structure.'),('Compare patterns','Find repeatable traits behind the successful references.'),('Deliver handoff','Clear recommendations for final production pipeline.')],'audio-spectral-analysis-review')

page('Odoo + Shopify Independent Audit Board','A fixed-fee audit workspace for reviewing Odoo v17 Enterprise + Shopify connector health: order flow, inventory sync, fulfillment lifecycle, webhook/API touchpoints, customization risks, and a prioritized issue register for a 10-day second-opinion engagement.','#a78bfa',[
('Audit intake map','Separate architecture facts from assumptions before touching production.',['Odoo modules/customizations','Shopify connector setup','fulfillment lifecycle states','known pain points and evidence']),
('Connector flow review','Map where orders, products, inventory, and fulfillment events can break.',['Shopify Admin API/webhooks','Odoo sales/order/inventory objects','sync retry/error handling','manual override points']),
('Risk register','Client gets prioritized findings, not a vague consultant memo.',['severity and business impact','reproduction steps','recommended fix owner','quick win vs structural issue']),
('10-day milestone plan','Keeps the audit scoped and fixed-fee.',['Day 1–2 access + mapping','Day 3–6 flow testing','Day 7–8 findings review','Day 9–10 final report + roadmap'])],
[('Engagement','10 days'),('Budget fit','$1,800 fixed'),('Focus','Second opinion'),('Output','Audit + roadmap')],
[('Map architecture','Odoo + Shopify objects, customizations and connector settings.'),('Trace lifecycle','Order → payment → inventory → fulfillment → refund/exception paths.'),('Log risks','Prioritized issue register with evidence and owner.'),('Deliver roadmap','What to fix now, what to defer, and what requires dev access.')],'odoo-shopify-audit-board')

print('generated')
