from pathlib import Path
root=Path('/Users/nani/workspace/upwork-job-demos/publish/art-catalog-mvp-automation')
root.mkdir(parents=True,exist_ok=True)
html=r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Art Catalog MVP Automation</title>
<style>
:root{--bg:#0d1117;--panel:#151b23;--panel2:#1f2937;--text:#e5eefb;--muted:#9aa7bd;--line:#2a3548;--a:#7dd3fc;--b:#a78bfa;--g:#34d399;--y:#fbbf24}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Arial;background:radial-gradient(circle at 20% 0,#1e1b4b 0,#0d1117 38%,#080b10 100%);color:var(--text)}main{max-width:1120px;margin:0 auto;padding:42px 20px}.badge{display:inline-flex;gap:8px;align-items:center;padding:8px 12px;border:1px solid #334155;border-radius:999px;background:#111827cc;color:#bfdbfe;font-size:13px}.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:24px;align-items:center;margin:22px 0 28px}.card{background:linear-gradient(180deg,#151b23f2,#0f1622f2);border:1px solid var(--line);border-radius:22px;padding:22px;box-shadow:0 18px 50px #0008}h1{font-size:48px;line-height:1.02;margin:16px 0 14px;letter-spacing:-1.5px}p{color:var(--muted);line-height:1.6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.step{border:1px solid var(--line);border-radius:18px;padding:18px;background:#111827b8}.step b{color:#fff}.tag{display:inline-block;padding:5px 9px;border-radius:999px;background:#0b2534;color:#7dd3fc;font-size:12px;margin:4px 4px 0 0}.flow{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-top:14px}.node{background:#0b1220;border:1px solid #263244;border-radius:16px;padding:14px;text-align:center}.node strong{display:block}.arrow{color:#60a5fa;font-size:24px;align-self:center;text-align:center}.table{width:100%;border-collapse:collapse;margin-top:12px;overflow:hidden;border-radius:14px}td,th{border-bottom:1px solid var(--line);padding:12px;text-align:left;color:#cbd5e1}th{color:#93c5fd;background:#0b1220}.mock{background:#050a12;border:1px solid #263244;border-radius:18px;padding:14px}.art{display:grid;grid-template-columns:80px 1fr auto;gap:12px;align-items:center;padding:12px;border-bottom:1px solid #1f2937}.thumb{width:80px;height:60px;border-radius:12px;background:linear-gradient(135deg,#f97316,#ec4899,#3b82f6)}.btn{border:0;border-radius:12px;background:linear-gradient(135deg,#2563eb,#7c3aed);color:white;padding:11px 14px;font-weight:700}.small{font-size:13px;color:#94a3b8}.ok{color:var(--g)}.warn{color:var(--y)}footer{margin-top:24px;color:#7f8da3;font-size:13px}@media(max-width:850px){.hero,.grid,.flow{grid-template-columns:1fr}h1{font-size:34px}.arrow{display:none}}</style>
</head><body><main>
<span class="badge">Proof-of-approach · No-code/low-code Art Catalog MVP · Fictional sample data</span>
<section class="hero">
 <div><h1>Artwork Upload → Metadata → Background → PDF Catalog → Email Delivery</h1><p>A lean MVP blueprint for an art catalog platform: artists/admins upload artworks, enrich metadata, select catalog backgrounds, generate PDF catalogs automatically, and send them by email with a clean delivery log.</p><div><span class="tag">Airtable / Sheets</span><span class="tag">Python PDF generation</span><span class="tag">API Integration</span><span class="tag">Email delivery</span><span class="tag">MVP workflow</span></div></div>
 <div class="card"><h3>What this proves</h3><p>Not a generic landing page — this maps the exact workflow from the job post into buildable MVP modules.</p><div class="flow"><div class="node"><strong>1</strong>Upload</div><div class="node"><strong>2</strong>Metadata</div><div class="node"><strong>3</strong>Background</div><div class="node"><strong>4</strong>PDF</div><div class="node"><strong>5</strong>Email</div></div></div>
</section>
<section class="grid">
 <div class="step"><b>Artwork Intake</b><p>Upload image, title, artist, dimensions, year, medium, price/status, and collection tags into a simple Airtable/Sheets-backed admin table.</p></div>
 <div class="step"><b>Catalog Builder</b><p>Select background/theme, choose artworks, sort order, cover text, and automatically compose a PDF-ready catalog structure.</p></div>
 <div class="step"><b>Delivery + QA Log</b><p>Generate PDF, send by email, record delivery status, and flag missing metadata or failed PDF/email steps before client-facing output.</p></div>
</section>
<section class="card" style="margin-top:18px"><h2>Sample MVP Data Model</h2><table class="table"><tr><th>Table</th><th>Key fields</th><th>Why it matters</th></tr><tr><td>Artworks</td><td>image_url, artist, title, medium, dimensions, year, price/status</td><td>Single source of truth for catalog pages</td></tr><tr><td>Catalogs</td><td>background_theme, selected_artwork_ids, order, cover copy, recipient list</td><td>Turns artwork records into repeatable PDF generation</td></tr><tr><td>Delivery Log</td><td>pdf_url, recipient, email_status, timestamp, error_message</td><td>Prevents “did it send?” confusion and supports retries</td></tr></table></section>
<section class="card" style="margin-top:18px"><h2>Mock Admin Queue</h2><div class="mock"><div class="art"><div class="thumb"></div><div><b>Blue Study No. 4</b><div class="small">Metadata complete · Background: Minimal White · Ready for PDF</div></div><button class="btn" onclick="demo('Generated PDF draft and queued email')">Generate</button></div><div class="art"><div class="thumb" style="background:linear-gradient(135deg,#22c55e,#14b8a6,#06b6d4)"></div><div><b>Garden Composition</b><div class="small">Missing dimensions · Needs review before catalog</div></div><button class="btn" onclick="demo('Flagged missing dimensions before PDF')">Check</button></div><div class="art"><div class="thumb" style="background:linear-gradient(135deg,#eab308,#f97316,#ef4444)"></div><div><b>Evening Line Work</b><div class="small">PDF generated · Email delivered · Logged</div></div><button class="btn" onclick="demo('Delivery log already complete')">View log</button></div><p id="out" class="ok"></p></div></section>
<section class="grid" style="margin-top:18px"><div class="step"><b>First milestone</b><p>Map fields, choose Airtable/Sheets structure, define PDF template rules, and build one catalog generation path with sample artworks.</p></div><div class="step"><b>Build approach</b><p>Start no-code/low-code for speed, use Python/API only where needed for reliable PDF generation and email delivery.</p></div><div class="step"><b>Handoff</b><p>Document the admin workflow so artwork upload, catalog creation, and delivery can be repeated without messy manual steps.</p></div></section>
<footer>Built as a job-specific proof-of-approach for Janis Agic's Upwork proposal. Uses fictional sample artwork data only.</footer>
</main><script>function demo(t){document.getElementById('out').textContent='✓ '+t}</script></body></html>'''
(root/'index.html').write_text(html,encoding='utf-8')
print(root/'index.html')
