#!/usr/bin/env python3
from pathlib import Path
from html import escape
BASE=Path('/Users/nani/workspace/upwork-job-demos')
PUB=BASE/'publish'
baseurl='https://janisag07.github.io/upwork-job-demos/publish'

jobs=[
 dict(slug='outbound-gtm-ops-command-center', title='Outbound GTM Operations Command Center', client='Marketing Ops team lead', budget='$3,500', color='#22c55e', stack=['Clay/LinkedIn enrichment','Email sequencing','HubSpot ops','AI personalization','Campaign reporting'], hero='A working-style command center for an outbound GTM team: ICP enrichment, AI-personalized sequences, QA, Slack-style tasks, and campaign reporting in one operating layer.', metrics=[('5 hrs/day','embedded ops lead'),('2 specialists','managed execution'),('4 campaigns','speaker/events/podcast/sales'),('0→1','clean operating system')], modules=['ICP + account enrichment queue with confidence checks','AI-assisted first-line and sequence copy QA before launch','HubSpot segmentation, tagging, lead flow and lifecycle partitions','Campaign scorecards for open/reply/meeting/event registration KPIs','Team task board so two specialists know exactly what to execute daily'], workflow=['Audit current outbound stack and ICP definitions','Map campaign types: speaker outreach, podcast booking, events, sales meetings','Build repeatable campaign templates and HubSpot lead routing','Add AI personalization/QA layer and reporting dashboard','Run weekly iteration loop based on replies and booked outcomes'], letter_angle='I focused the proof on the operating system behind the outbound engine: enrichment, sequencing, HubSpot routing, team execution, and reporting.'),
 dict(slug='whatsapp-affiliate-retention-os', title='WhatsApp Affiliate Retention OS', client='WhatsApp Community & Automation Manager', budget='$2,000', color='#25d366', stack=['WhatsApp automation','Affiliate onboarding','Retention CRM','Broadcasts','Lifecycle segmentation'], hero='A WhatsApp-first retention and community system for affiliate/customer lifecycle journeys — onboarding, activation, events, re-engagement, broadcasts, and KPI tracking.', metrics=[('6 journeys','onboarding→winback'),('Opt-in/out','compliance layer'),('24/7','triggered flows'),('CRM','behavior segments')], modules=['New affiliate onboarding and activation drip flows','Customer retention, promo and event broadcast calendars','Behavior-based segments: new, active, dormant, VIP, support-needed','Opt-in/opt-out guardrails and frequency caps','Performance dashboard for reads, clicks, conversions and retention'], workflow=['Map lifecycle stages and required WhatsApp touchpoints','Design template library for onboarding/promos/events/support','Set up segmentation and trigger logic against CRM data','Create community moderation/announcement workflow','Launch with KPI tracking and weekly optimization loop'], letter_angle='I built the proof around lifecycle messaging, not just WhatsApp blasts: onboarding, segmentation, broadcasts, compliance, and retention analytics.'),
 dict(slug='retirement-lead-funnel-facebook', title='Retirement Lead Funnel & Appointment Engine', client='Senior Performance Marketer Facebook Lead Funnel', budget='$1,000', color='#60a5fa', stack=['Facebook lead ads','Landing funnel','CRM automation','Appointment booking','Lead nurture'], hero='A lead-generation funnel for the turning-65 retirement audience: ad-to-lead capture, qualification, nurture, booked appointments, and daily optimization metrics.', metrics=[('Turning 65','target segment'),('Lead→Call','booking route'),('SMS/email','nurture layer'),('Daily','performance review')], modules=['Lead magnet / offer framing for retirement-age prospects','Facebook/Instagram lead capture flow with clear consent language','Qualification questions and CRM scoring','Automated SMS/email follow-up until booked appointment','Dashboard for CPL, booked rate, no-show risk and funnel bottlenecks'], workflow=['Clarify offer, audience exclusions and compliance-sensitive wording','Build lead form/landing flow and CRM fields','Set up immediate follow-up and appointment booking path','Create reporting view for lead quality and booked calls','Iterate creative/form questions based on booked appointment data'], letter_angle='I made the proof specific to a retirement lead funnel: targeting, lead qualification, booking, follow-up, and measurable booked appointment outcomes.'),
 dict(slug='scrape-transform-upload-pipeline', title='Scrape → Transform → Upload Data Pipeline', client='Web Scraping Specialist Data Extraction and Upload', budget='$1,500', color='#f59e0b', stack=['Python scraping','Data cleaning','Deduplication','Upload workflow','QA reports'], hero='A clean extraction pipeline concept that turns messy website data into validated, transformed records ready for upload into the client platform.', metrics=[('3 stages','extract/clean/upload'),('QA','duplicates + missing fields'),('Retry','error handling'),('CSV/API','handoff ready')], modules=['Source parser with polite rate limiting and extraction logs','Transformation rules for categories, titles, prices, images and attributes','Duplicate detection and missing-field review queue','Upload staging table with status, errors and retry actions','Final QA export/report so the client can verify exactly what changed'], workflow=['Confirm target website, fields, platform upload method and allowed access','Build extractor for a small verified sample first','Normalize/transform data into the required schema','Run QA: duplicates, missing values, invalid records, failed uploads','Deliver repeatable script + upload logs + handoff notes'], letter_angle='I focused the proof on reliability: extraction logs, transformation rules, duplicate checks, upload statuses, and a small verified sample first.'),
 dict(slug='whatsapp-service-marketplace-backend', title='WhatsApp Service Marketplace Backend', client='Python Backend Developer for WhatsApp Service Marketplace', budget='$2,000', color='#10b981', stack=['FastAPI','Supabase/Postgres','WhatsApp Cloud API','OpenAI routing','Provider matching'], hero='A backend architecture preview for a UAE WhatsApp service marketplace: intent detection, provider matching, conversation state, escalation, and admin visibility.', metrics=[('FastAPI','backend core'),('Supabase','data layer'),('WhatsApp','Cloud API'),('AI','intent router')], modules=['Conversation state machine for service requests inside WhatsApp','OpenAI-based intent extraction with safe confidence fallback','Provider matching by category, location, availability and rating','Admin panel view for requests, providers, handoffs and failed conversations','Webhook/security plan for Meta WhatsApp Cloud API events'], workflow=['Lock entities: consumers, providers, categories, requests, messages','Build FastAPI webhook receiver and Supabase schema','Implement intent extraction + provider matching + fallback flows','Create admin monitoring endpoints and seed/demo data','Test core paths: new request, match found, clarification, human handoff'], letter_angle='I made the proof match your stated stack: FastAPI, Supabase, WhatsApp Cloud API, and an AI intent/provider matching layer.'),
]

def page(j):
    c=j['color']
    chips=''.join('<span>'+escape(x)+'</span>' for x in j['stack'])
    metrics=''.join('<div class="metric"><b>'+escape(a)+'</b><span>'+escape(b)+'</span></div>' for a,b in j['metrics'])
    modules=''.join('<li>'+escape(x)+'</li>' for x in j['modules'])
    flow=''.join('<div class="step"><strong>%02d</strong><p>%s</p></div>'%(i,escape(x)) for i,x in enumerate(j['workflow'],1))
    rows=''.join('<div class="row"><em></em><div><b>'+escape(x.split()[0])+'</b><small>'+escape(x)+'</small></div></div>' for x in j['modules'][:4])
    html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Arial;background:radial-gradient(circle at 10% 0%,__COLOR__44,transparent 32%),linear-gradient(180deg,#07111f,#0a0f18 55%,#05070b);color:#f8fafc}.wrap{max-width:1180px;margin:auto;padding:44px 20px}.hero{display:grid;grid-template-columns:1.05fr .95fr;gap:24px;align-items:stretch}.badge{display:inline-flex;border:1px solid __COLOR__88;background:__COLOR__18;color:#e5e7eb;padding:9px 13px;border-radius:999px;font-size:13px}h1{font-size:clamp(36px,6vw,72px);line-height:.95;letter-spacing:-.06em;margin:18px 0}.lead{font-size:20px;line-height:1.55;color:#cbd5e1;max-width:760px}.disc{margin:18px 0;padding:13px 15px;border:1px solid #334155;background:#0f172acc;border-radius:16px;color:#cbd5e1;font-size:13px}.chips{display:flex;flex-wrap:wrap;gap:10px}.chips span{border:1px solid #334155;background:#111827;padding:10px 12px;border-radius:999px;color:#dbeafe;font-size:13px}.panel,.phone{background:linear-gradient(180deg,#111827,#0b1220);border:1px solid #263244;border-radius:28px;padding:24px;box-shadow:0 24px 80px #0008}.phone{min-height:520px;position:relative;overflow:hidden}.phone:before{content:'';position:absolute;inset:18px;border-radius:24px;border:1px solid #334155;background:linear-gradient(180deg,#0f172a,#050816)}.phone>*{position:relative}h2{font-size:28px;margin:0 0 16px;letter-spacing:-.03em}.row{display:flex;gap:13px;padding:13px;border:1px solid #263244;background:#0b1220;border-radius:18px;margin:11px 0}.row em{width:12px;height:12px;border-radius:50%;background:__COLOR__;margin-top:4px;box-shadow:0 0 24px __COLOR__}.row b{display:block}.row small{color:#94a3b8;line-height:1.4}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.metric{padding:18px;border:1px solid #263244;background:#0b1220;border-radius:22px}.metric b{display:block;font-size:26px;color:__COLOR__}.metric span{font-size:13px;color:#94a3b8}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}li{margin:10px 0;color:#dbeafe;line-height:1.5}.step{display:flex;gap:14px;padding:13px 0;border-top:1px solid #263244}.step strong{color:__COLOR__}.step p{margin:0;color:#cbd5e1}.cta{margin-top:18px;padding:16px;border-radius:20px;background:__COLOR__1f;border:1px solid __COLOR__77;color:#ecfeff}@media(max-width:850px){.hero,.grid{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}h1{font-size:42px}.phone{min-height:auto}}
</style></head><body><main class="wrap"><section class="hero"><div><div class="badge">Premium proof for Upwork · __BUDGET__ · fictional demo data</div><h1>__TITLE__</h1><p class="lead">__HERO__</p><div class="disc">Disclaimer: All displayed data, names, messages, and metrics are fictional and shown for visual demonstration purposes only.</div><div class="chips">__CHIPS__</div></div><aside class="phone"><h2>Workflow preview</h2>__ROWS__<div class="cta"><b>Delivery angle:</b> fast MVP first, clean handoff notes, and business metrics visible from day one.</div></aside></section><section class="metrics">__METRICS__</section><section class="grid"><div class="panel"><h2>What I would build</h2><ul>__MODULES__</ul></div><div class="panel"><h2>Execution plan</h2>__FLOW__</div></section></main></body></html>'''
    return html.replace('__COLOR__',c).replace('__TITLE__',escape(j['title'])).replace('__BUDGET__',escape(j['budget'])).replace('__HERO__',escape(j['hero'])).replace('__CHIPS__',chips).replace('__ROWS__',rows).replace('__METRICS__',metrics).replace('__MODULES__',modules).replace('__FLOW__',flow)

for j in jobs:
    d=PUB/j['slug']; d.mkdir(parents=True, exist_ok=True)
    (d/'index.html').write_text(page(j), encoding='utf-8')

(BASE/'DEMO_PLAN_SUPER_JOBS_2026-05-03.md').write_text('# Super Jobs Upwork batch — 2026-05-03\n\n'+'\n'.join(f"- {j['client']} — {j['budget']} — publish/{j['slug']}/" for j in jobs)+'\n', encoding='utf-8')
with (BASE/'proposal_drafts_super_jobs_2026-05-03.md').open('w',encoding='utf-8') as f:
    f.write('# Proposal drafts — Super Jobs 2026-05-03\n\n')
    for j in jobs:
        url=f"{baseurl}/{j['slug']}/index.html"
        f.write(f"## {j['client']}\nURL: {url}\n\nHi,\n\nI can help with this. I put together a quick proof-of-approach for your project so you can see how I would structure the first version before we start:\n{url}\n\n{j['letter_angle']}\n\nMy approach would be simple: ship a useful MVP quickly, keep the workflow easy for your team to maintain, and document the handoff so it does not become a black box.\n\nIf you want, I can start with a focused first milestone and then improve it based on real data/results.\n\nBest,\nJanis\n\n")
print('created', len(jobs), 'demos and proposal drafts')
